Update sources location references
glpi-project/docdev pull request #139
Opened 2023-06-06 16:47 UTC by cconard96

Classes are now in `src` and it should be the preferred folder for classes in plugins as well. Additionally, namespaces should be supported for most things now and should be recommended for plugins instead of using classes with the `PluginMyplugin` prefix on the classes in the global namespace.

2023-06-06 19:19 UTC, cedric-anne requested changes

2023-06-06 19:19 UTC, cedric-anne commented on source/devapi/rules.rst
> +* ``src/RuleMytypeCollection.class.php``
```suggestion
* ``src/RuleMytypeCollection.php``
```

2023-06-06 19:19 UTC, cedric-anne commented on source/plugins/notifications.rst
> +That said, we need to create a class to handle the settings, and a front file to display them. The class must be named ``GlpiPlugin\Sms\NotificationSmsSetting`` and must be in the ``src/NotificationS
```suggestion
That said, we need to create a class to handle the settings, and a front file to display them. The class must be named ``GlpiPlugin\Sms\NotificationSmsSetting`` and must be in the ``src/NotificationSmsSetting.php`` file. It have to extends the ``NotificationSetting`` core class :
```

2023-06-06 19:19 UTC, cedric-anne commented on source/plugins/notifications.rst
> +Once the new mode has been enabled; it will try to raise core events. You will need to create an event class named ``GlpiPlugin\Sms\NotificationEventSms`` that implements ``NotificationEventInterface
```suggestion
Once the new mode has been enabled; it will try to raise core events. You will need to create an event class named ``GlpiPlugin\Sms\NotificationEventSms`` that implements ``NotificationEventInterface`` and extends ``NotificationEventAbstract`` in the ``src/NotificationEventSms.php`` file.
```

2023-06-06 19:19 UTC, cedric-anne commented on source/plugins/objects.rst
> +First, create the ``src/MyObject.class.php`` file that looks like:
```suggestion
First, create the ``src/MyObject.php`` file that looks like:
```

2023-06-06 19:19 UTC, cedric-anne commented on source/plugins/tips.rst
> +Just add the following to your object class (``src/MyObject.class.php``):
```suggestion
Just add the following to your object class (``src/MyObject.php``):
```

2023-06-21 06:28 UTC, cedric-anne approved these changes

2023-06-21 06:36 UTC, trasher approved these changes

2023-06-21 06:36 UTC, merged