Update db iterator docs
glpi-project/docdev pull request #141
Opened 2023-06-07 01:04 UTC by cconard96

- Update docs regarding SQL functions to reflect the new way to handle them in GLPI 10.1.
- Remove references to specifying the table in the first parameter of the `request` method as it has been deprecated for a while.
- Added a few clarifications regarding array values in criteria, null values, etc.

2023-06-07 06:15 UTC, orthagh approved these changes

2023-06-07 06:44 UTC, trasher requested changes

2023-06-07 06:44 UTC, trasher commented on source/devapi/database/dbiterator.rst
> +   $DB->request('glpi_computers', 'WHERE' => ['is_deleted' => 0,
I think this is wrong; `WHERE` is not an array key here. Anyways, you've replaced syntax with `FROM` array key; I think you can replace it everywhere

2023-06-07 06:45 UTC, trasher commented on source/devapi/database/dbiterator.rst
> +         'date_end'  => ['>', Glpi\DBAL\QueryFunction::now()]
```suggestion
         'date_end'  => ['>', \Glpi\DBAL\QueryFunction::now()]
```

2023-06-07 10:44 UTC, cedric-anne requested changes
Changes related to `\Glpi\DBAL\QueryFunction` should be part of another PR and should clearly identified with `.. versionadded:: 10.1.0`/`.. versionchanged:: 10.1.0`.

Also, they should be merged in `develop` branch for now.

2023-06-08 05:26 UTC, trasher approved these changes

2023-06-08 06:37 UTC, cedric-anne approved these changes

2023-06-08 06:37 UTC, merged